baseURL: http://zerowzl.com/
title: 个人技术文章
languageCode: zh-cn # en-us
theme: paperMod


enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

paginate: 5    # 首页每页显示的文章数

minify:
    disableXML: true

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30

params:
  homeInfoParams:
    Title: "个人技术文章"
    Content: >
        欢迎来到我的主页。我会在这里分享 IT 技术文章，个人经验。欢迎订阅~
